name: Build Windows Game

on:
  workflow_dispatch:
    inputs:
      build-defines:
        type: string
        description: Build defines to use
        default: "-DGITHUB_BUILD"

  push:
    branches:
      - develop

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    env:
      BUILD_DEFINES: ${{ github.event.inputs.build-defines || '-DGITHUB_BUILD' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Setup Haxelib
        run: |
          haxelib setup C:/haxelib

      - name: Install dependencies
        run: |
          git config --global advice.detachedHead false
          haxelib --global git haxelib https://github.com/FunkinCrew/haxelib.git
          haxelib --global git hmm https://github.com/FunkinCrew/hmm.git
          haxelib --global run hmm install -q
          haxelib --global fixrepo
          haxelib --global list

      - name: Build HXCPP Tools
        run: |
          pushd .haxelib/hxcpp/git/tools/hxcpp
          haxe compile.hxml
          popd

      - name: Setup Lime
        run: |
          haxelib --always run lime setup
          haxelib run lime rebuild hxcpp
          haxelib run lime rebuild cpp -64

      - name: Build Windows
        run: |
          haxelib run lime build windows -v -release $BUILD_DEFINES
        timeout-minutes: 120

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: funkin-windows
          path: export/release/windows/bin/
