name: Build Windows

on:
  workflow_dispatch:
    inputs:
      build-defines:
        type: string
        description: Build defines
        default: "-DGITHUB_BUILD"

  push:
    branches:
      - develop

jobs:
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: bash

    env:
      BUILD_DEFINES: ${{ github.event.inputs.build-defines || '-DGITHUB_BUILD' }}

    steps:
      - name: Make git happy
        run: |
          git config --global --replace-all safe.directory $GITHUB_WORKSPACE

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Haxe Environment
        uses: ./.github/actions/setup-haxe
        with:
          gh-token: ${{ github.token }}
          targets: windows

      - name: Build HXCPP Tools
        run: |
          pushd .haxelib/hxcpp/git/tools/hxcpp
          haxe compile.hxml
          popd

      - name: Setup Lime
        run: |
          haxelib --always run lime setup
          haxelib run lime rebuild cpp

      - name: Populate .env
        run: |
          touch .env

      - name: Build Windows
        run: |
          haxelib run lime build windows -v -release $BUILD_DEFINES
        timeout-minutes: 120

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: funkin-windows
          path: export/release/windows/bin/
